---
# tasks file for netzwirt.simple-pki
# create user requests and certs

- name: create users requests
  shell: PKI_FULLNAME="{{item.fullname|trim}}" PKI_EMAIL="{{item.email|trim}}" openssl req -new
      -config {{simplepki_conf_dir|trim}}/user.conf
      -out {{item.username|trim}}{{simplepki_file_ext_csr}}
      -keyout {{item.username|trim}}{{simplepki_file_ext_key}}
    creates="{{item.username|trim}}{{simplepki_file_ext_key}}"
    executable=/bin/bash
    chdir="{{simplepki_certs_dir}}"
  with_items: "{{simplepki_user_certs}}"

- name: sign users requests
  shell: openssl ca
      -config {{simplepki_conf_dir|trim}}/{{simplepki_signing_ca_name|trim}}.conf
      -in {{item.username|trim}}{{simplepki_file_ext_csr}}
      -out {{item.username|trim}}{{simplepki_file_ext_crt}}
      -extensions user_ext
      -batch
    creates="{{item.username|trim}}{{simplepki_file_ext_crt}}"
    executable=/bin/bash
    chdir="{{simplepki_certs_dir}}"
  with_items: "{{simplepki_user_certs}}"

- name: protect users keys
  file:
    path="{{simplepki_certs_dir|trim}}/{{item.username|trim}}{{simplepki_file_ext_key}}"
    owner=root
    group=root
    mode=0400
  with_items: "{{simplepki_user_certs}}"

- name: fetch client keys
  fetch:
    src="{{simplepki_certs_dir|trim}}/{{item.username|trim}}{{simplepki_file_ext_key}}"
    dest={{simplepki_fetch_pki_dir}}/{{inventory_hostname}}/clients/{{item.username|trim}}{{simplepki_file_ext_key}}
    flat=yes
  with_items: "{{simplepki_user_certs}}"
  when: "{{simplepki_fetch_pki_users_keys}}"

- name: fetch client certs
  fetch:
    src="{{simplepki_certs_dir|trim}}/{{item.username|trim}}{{simplepki_file_ext_crt}}"
    dest={{simplepki_fetch_pki_dir}}/{{inventory_hostname}}/clients/{{item.username|trim}}{{simplepki_file_ext_crt}}
    flat=yes
  with_items: "{{simplepki_user_certs}}"
  when: "{{simplepki_fetch_pki_users_certs}}"
